   image: node:latest

   stages:
     - lint
     - test

   cache:
     paths:
       - node_modules/

   before_script:
     - npm install

   eslint:
     stage: lint
     script:
       - npx eslint "src/**/*.{js,jsx,tsx}"

   jest:
     stage: test
     script:
       - npx jest
